### ISSUE TITLE
Helm repository for the retina

### ISSUE THREAD

**Issue by seilorjunior** [microsoft/retina#107]
**Is your feature request related to a problem? Please describe.**
Currently, setting up installations in a cluster involves several steps to obtain the manifests for the helm. This process includes acquiring various tools locally and executing multiple commands, leading to complexity and potential errors.

**Describe the solution you'd like**
I envision a straightforward installation process for Retina. Simplifying the setup to just a few steps would greatly enhance user experience.

**Describe alternatives you've considered**
One feasible alternative is to establish a dedicated repository for Retina manifests. By adding this repository to Helm, users could easily access and install Retina with minimal effort:
```
helm repo add retinarepository
helm install retina
```

**Additional context**
Implementing this solution could significantly reduce the occurrence of issues that need to be investigated, streamlining the deployment process for Retina.

**Comment by rbtr** [comment]
there are some options for how we could handle this:
- use GH pages to host a helm repo (may be challenging, because we use GH pages to host retina.sh)
- use something like artifacthub
- publish [helm charts as OCI](https://helm.sh/docs/topics/registries/) artifacts to GHCR

I favor the last option and it would be straightforward to set up, but interested to see what others think about the UX there, or if there are other options I haven't listed

**Comment by rbtr** [comment]
will be fixed in https://github.com/microsoft/retina/pull/127 by publishing the helm chart OCI artifact to GHCR
