### ISSUE TITLE
chart publishing is failing

### ISSUE THREAD

**Issue by nddq** [microsoft/retina#1081]
![Image](https://github.com/user-attachments/assets/7fd16606-6b5a-4db4-b13e-2b85a95d685f)
since v0.0.18

**Comment by SRodi** [comment]
as discussed off line with @nddq - we will be publishing v0.0.19 soon to publish a chart for the latest release. It appears the issue is due to tag `v0.0.18` and `v0.0.17` both referring to the same commit [cf0e69a](https://github.com/microsoft/retina/commit/cf0e69ae1c2a34c8aecd2a26bf99939b935637a7)

**Comment by SRodi** [comment]
chart publishing: https://github.com/microsoft/retina/actions/runs/12054996920

release v0.0.19: https://github.com/microsoft/retina/releases/tag/v0.0.19

![Image](https://github.com/user-attachments/assets/0044fe92-0191-459f-83cf-48c65cdd6229)
