### ISSUE TITLE
flannel.1 and cni0 interfaces don't support ethtool

### ISSUE THREAD

**Issue by CecileRobertMichon** [microsoft/retina#296]
**Describe the bug**

Seeing repeated errors like this in retina agent logs:

```
ts=2024-04-19T05:32:58.687Z level=error caller=linuxutil/ethtool_stats_linux.go:73 msg="Error while getting ethtool:" [redacted] plugins=dropreason,packetforward,linuxutil,dns,packetparser ifacename=flannel.1 error="operation not supported"
ts=2024-04-19T05:32:58.695Z level=error caller=linuxutil/ethtool_stats_linux.go:73 msg="Error while getting ethtool:"  [redacted]  plugins=dropreason,packetforward,linuxutil,dns,packetparser ifacename=cni0 error="operation not supported"
```

The error seems to be coming from https://github.com/microsoft/retina/blob/96d42f9e6439ed6d12821ef416983df5165ccbb1/pkg/plugin/linuxutil/ethtool_stats_linux.go#L73

Retina is already skipping some loopback and bridget interfaces https://github.com/microsoft/retina/blob/96d42f9e6439ed6d12821ef416983df5165ccbb1/pkg/plugin/linuxutil/ethtool_stats_linux.go#L67 but this may not be enough based on env. 

Would it be possible to exclude these interfaces as well? Or would it be preferable to make the interfaces to skip configurable somehow? Happy to open a PR if that's the case but hoping for a bit of guidance so I don't head the wrong direction. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**

- OS: [e.g. AzureLinux]
- Kubernetes Version: [e.g. 1.22]
- Host: [e.g. AKS, KIND, self-host, etc]
- Retina Version:

**Additional context**

**Comment by vakalapa** [comment]
thank you for the issue. Ideally it would better to have a dynamic way of detecting which interfaces do not support this operation. One way i can think of is, instead of printing/logging error, once we detect an error, retina can maintain a list of interfaces to ignore getting ethtool stats next time. Open to any other suggestions here. 

A configurable list of metrics sounds good, but this will put extra burden on the user.
