### ISSUE TITLE
improve docs for Grafana deployment 

### ISSUE THREAD

**Issue by SRodi** [microsoft/retina#758]
The doc https://retina.sh/docs/Installation/Grafana/grafana/ is not very clear and the instructions for https://retina.sh/docs/Installation/Grafana/prometheus-unmanaged are re-directing the user to Grafana cloud to create a new dashboard.

## Question
Why are we re-directing the user to Grafana Cloud?

## Proposal

1. restructure the document to separate Prometheus deployment and Grafana deployment
2. provide instructions on how to deploy Grafana via Helm for consistency (since we already do that for Prometheus ) 
3. provide instructions on how to configure Prometheus data source in Grafana and create Kubernetes dashboard

## References

* https://grafana.com/docs/grafana/latest/setup-grafana/installation/helm/

**Comment by vakalapa** [comment]
@SRodi Proposal makes sense, we need to be more explicit in saying BYO grafana can be deployed anywhere. Even in cluster would work. Ideally we should enhance this to show how to install grafana instance in cluster which can be port forwarded. I will accept this issue, can you assign this to your self and fix it ?

**Comment by whatnick** [comment]
Perhaps also worth adding the generation of [configmaps](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/configGeneration.md) from dashboard JSON's included in the repository for Grafana to scan and automatically create relevant dashboards.

**Comment by rbtr** [comment]
Just to note since you have said
> 2. provide instructions on how to deploy Grafana via Helm for consistency (since we already do that for Prometheus)

The `kube-prometheus` chart includes Grafana. By following the instructions in [Prometheus Unmanaged](https://retina.sh/docs/Installation/Grafana/prometheus-unmanaged/) to set up self-hosted Prometheus stack, you have already installed Grafana by the time you get to the "Configuring Grafana" steps. IMO, this section should be rewritten to actually be _configuring_ the instance, and not mention SaaS Grafana or any further install steps that maybe saying you can access the instance you just installed by `kubectl port-forward svc/prometheus-grafana 8080:80`.
