### ISSUE TITLE
Investigate errors while building agent image

### ISSUE THREAD

**Issue by anubhabMajumdar** [microsoft/retina#970]
**Describe the bug**

The `go mod tidy` step is throwing errors. Investigate why and remove the errors.

**To Reproduce**

Pipeline - https://github.com/microsoft/retina/actions/runs/11725715065/job/32662674487#step:8:568

**Expected behavior**

No errors.

**Screenshots**

![Image](https://github.com/user-attachments/assets/336656e1-c5ee-498f-a8cb-1f0b09a6041a)

**Platform (please complete the following information):**

- OS: Linux
- Kubernetes Version: [e.g. 1.22]
- Host: [e.g. AKS, KIND, self-host, etc]
- Retina Version:

**Additional context**

**Comment by timraymond** [comment]
One problem is that we shouldn't be using `go mod tidy` at all in any build pipeline or container build. `go build -mod=readonly` is the correct way to auto-fetch dependencies.

**Comment by timraymond** [comment]
This was not `go mod tidy` -- that's only a suggestion from the output of the Go toolchain. The problem here is `go generate` is running `mockgen`, which is only used for tests. The `go generate` lines invoking `mockgen` should only be invoked locally and their byproducts should be checked in. There's no reason to run these in pipelines--it's just a waste of compute.
